export const matters = [
  {
    id: 1,
    caseNumber: '2024-001',
    title: 'Labor lawsuit vs Ramon Torres',
    client: 'Northern Construction LLC',
    type: 'Labor',
    status: 'In Progress',
    openedAt: '2024-01-15',
    attorney: 'Maria Rodriguez',
  },
  {
    id: 2,
    caseNumber: '2024-002',
    title: 'Divorce proceedings - Familia Jimenez',
    client: 'Roberto Familia Jimenez',
    type: 'Civil',
    status: 'In Progress',
    openedAt: '2024-02-03',
    attorney: 'Jorge Perez',
  },
  {
    id: 3,
    caseNumber: '2024-003',
    title: 'Contractual dispute with supplier XYZ',
    client: 'Star Supermarkets Inc.',
    type: 'Commercial',
    status: 'Open',
    openedAt: '2024-03-20',
    attorney: 'Maria Rodriguez',
  },
  {
    id: 4,
    caseNumber: '2023-047',
    title: 'Vasquez inheritance claim',
    client: 'Carmen Vasquez Herrera',
    type: 'Civil',
    status: 'Closed',
    openedAt: '2023-06-01',
    attorney: 'Jorge Perez',
  },
  {
    id: 5,
    caseNumber: '2024-004',
    title: 'Trademark infringement - BrandCo',
    client: 'BrandCo International',
    type: 'Commercial',
    status: 'On Hold',
    openedAt: '2024-04-10',
    attorney: 'Ana Martinez',
  },
  {
    id: 6,
    caseNumber: '2024-005',
    title: 'Amparo constitucional - Derechos laborales',
    client: 'Union de Trabajadores',
    type: 'Constitutional',
    status: 'Open',
    openedAt: '2024-04-18',
    attorney: 'Maria Rodriguez',
  },
];

export const clients = [
  {
    id: 1,
    name: 'Northern Construction LLC',
    type: 'LegalEntity',
    idNumber: '1-30-12345-6',
    email: 'legal@constructionnorth.com',
    phone: '809-555-0101',
    activeCases: 2,
    createdAt: '2023-01-10',
  },
  {
    id: 2,
    name: 'Roberto Familia Jimenez',
    type: 'Individual',
    idNumber: '001-0234567-8',
    email: 'rfamilia@email.com',
    phone: '809-555-0202',
    activeCases: 1,
    createdAt: '2024-01-28',
  },
  {
    id: 3,
    name: 'Star Supermarkets Inc.',
    type: 'LegalEntity',
    idNumber: '1-30-98765-4',
    email: 'management@star.com',
    phone: '809-555-0303',
    activeCases: 1,
    createdAt: '2024-03-15',
  },
  {
    id: 4,
    name: 'Carmen Vasquez Herrera',
    type: 'Individual',
    idNumber: '223-0012345-6',
    email: 'cvasquez@email.com',
    phone: '809-555-0404',
    activeCases: 0,
    createdAt: '2023-05-20',
  },
  {
    id: 5,
    name: 'BrandCo International',
    type: 'LegalEntity',
    idNumber: '1-30-11111-2',
    email: 'legal@brandco.com',
    phone: '809-555-0505',
    activeCases: 1,
    createdAt: '2024-04-05',
  },
  {
    id: 6,
    name: 'Union de Trabajadores',
    type: 'LegalEntity',
    idNumber: '1-30-22222-3',
    email: 'contacto@uniontrab.com',
    phone: '809-555-0606',
    activeCases: 1,
    createdAt: '2024-04-15',
  },
];

export const documents = [
  {
    id: 1,
    title: 'Initial labor complaint',
    matter: '2024-001',
    category: 'Complaint',
    version: 2,
    uploadedBy: 'Maria Rodriguez',
    updatedAt: '2024-01-20',
    fileType: 'pdf',
    sizeMb: 0.24,
  },
  {
    id: 2,
    title: 'Original employment contract',
    matter: '2024-001',
    category: 'Contract',
    version: 1,
    uploadedBy: 'Maria Rodriguez',
    updatedAt: '2024-01-18',
    fileType: 'pdf',
    sizeMb: 0.18,
  },
  {
    id: 3,
    title: 'Termination letter',
    matter: '2024-001',
    category: 'Correspondence',
    version: 1,
    uploadedBy: 'Ana Martinez',
    updatedAt: '2024-01-22',
    fileType: 'pdf',
    sizeMb: 0.1,
  },
  {
    id: 4,
    title: 'Marriage certificate',
    matter: '2024-002',
    category: 'Minutes',
    version: 1,
    uploadedBy: 'Jorge Perez',
    updatedAt: '2024-02-08',
    fileType: 'pdf',
    sizeMb: 0.31,
  },
  {
    id: 5,
    title: 'Property separation agreement',
    matter: '2024-002',
    category: 'Contract',
    version: 2,
    uploadedBy: 'Jorge Perez',
    updatedAt: '2024-02-15',
    fileType: 'docx',
    sizeMb: 0.09,
  },
  {
    id: 6,
    title: 'Supplier contract XYZ',
    matter: '2024-003',
    category: 'Contract',
    version: 1,
    uploadedBy: 'Maria Rodriguez',
    updatedAt: '2024-03-22',
    fileType: 'pdf',
    sizeMb: 0.4,
  },
  {
    id: 7,
    title: 'Court order - preliminary',
    matter: '2024-001',
    category: 'Court Order',
    version: 1,
    uploadedBy: 'Maria Rodriguez',
    updatedAt: '2024-03-16',
    fileType: 'pdf',
    sizeMb: 0.15,
  },
];

export const hearings = [
  {
    id: 1,
    title: 'Merits hearing',
    matter: '2024-001',
    client: 'Northern Construction LLC',
    court: 'National District Labor Court, Room 3',
    date: '2024-05-20',
    time: '10:30',
    status: 'Pending',
    attorney: 'Maria Rodriguez',
  },
  {
    id: 2,
    title: 'Agreement ratification',
    matter: '2024-002',
    client: 'Roberto Familia Jimenez',
    court: 'National District Family Court, Room 1',
    date: '2024-06-12',
    time: '09:00',
    status: 'Pending',
    attorney: 'Jorge Perez',
  },
  {
    id: 3,
    title: 'Conciliation hearing',
    matter: '2024-003',
    client: 'Star Supermarkets Inc.',
    court: 'Commercial Court, Room 2',
    date: '2024-04-25',
    time: '11:00',
    status: 'Postponed',
    attorney: 'Maria Rodriguez',
  },
  {
    id: 4,
    title: 'Preliminary hearing',
    matter: '2024-001',
    client: 'Northern Construction LLC',
    court: 'National District Labor Court, Room 3',
    date: '2024-03-15',
    time: '09:00',
    status: 'Held',
    attorney: 'Maria Rodriguez',
  },
  {
    id: 5,
    title: 'First appearance',
    matter: '2024-002',
    client: 'Roberto Familia Jimenez',
    court: 'National District Family Court, Room 1',
    date: '2024-04-08',
    time: '08:30',
    status: 'Held',
    attorney: 'Jorge Perez',
  },
  {
    id: 6,
    title: 'Constitutional review',
    matter: '2024-005',
    client: 'Union de Trabajadores',
    court: 'Constitutional Court, Chamber A',
    date: '2024-06-30',
    time: '14:00',
    status: 'Pending',
    attorney: 'Maria Rodriguez',
  },
];

export const dashboardStats = {
  activeMatters: 4,
  totalClients: 6,
  upcomingHearings: 3,
  totalDocuments: 7,
};
